package consola;

public class App {

	/*
	 		CREATE TABLE PEDIDO(
		 			ID NUMBER(5) PRIMARY KEY,
		 			FECHA DATE NOT NULL,
		 			INFO VARCHAR2(100) NOT NULL,
		 			IDCLIENTE NUMBER(5) REFERENCES CLIENTE(ID) NOT NULL
		 		);
		 		
		 		INSERT INTO PEDIDO (ID, FECHA, INFO, IDCLIENTE)
		 				VALUES(1, '1/5/2015', 'Pedido 1', 1);
		 		INSERT INTO PEDIDO (ID, FECHA, INFO, IDCLIENTE)
		 				VALUES(2, '11/5/2015', 'Pedido 2', 1);
		 		INSERT INTO PEDIDO (ID, FECHA, INFO, IDCLIENTE)
		 				VALUES(3, '03/10/2015', 'Pedido 3', 2);
		 				
		 		CREATE OR REPLACE PROCEDURE INSERTA_PEDIDO
		 			(NOMBRE_CLIENTE VARCHAR2, PFECHA DATE, PINFO VARCHAR2)
		 		IS
		 		BEGIN
		 			INSERT INTO PEDIDO (ID, FECHA, INFO, IDCLIENTE)
		 				VALUES((SELECT NVL(MAX(ID),0) + 1 FROM PEDIDO), PFECHA, PINFO, 
		 						(SELECT ID FROM CLIENTE WHERE NOMBRE = NOMBRE_CLIENTE)
		 				);
		 		END;
		 		/
		 		 
		 		CREATE OR REPLACE FUNCTION NOMBRE_DE_CLIENTE (ID_CLIENTE NUMBER)
		 		RETURN VARCHAR2
		 		IS
		 			VNOMBRE CLIENTE.NOMBRE%TYPE;
		 		BEGIN
		 			SELECT NOMBRE INTO VNOMBRE FROM CLIENTE WHERE ID = ID_CLIENTE;
		 			RETURN VNOMBRE;
		 		END;
		 		/
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
	}
}//finc class consola.App
